# 配置入口 公共配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/wxsell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update